// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma 7 config
import "dotenv/config"
import { defineConfig } from "prisma/config"

export default defineConfig({
  // Caminho do schema
  schema: "prisma/schema.prisma",

  // Configuração de migrations e seed
  migrations: {
    path: "prisma/migrations",
    seed: 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },

  datasource: { url: process.env["DATABASE_URL"] },

  // Prisma 7: NÃO definir datasource aqui quando usar adapter no runtime
  // O datasource deve vir EXCLUSIVAMENTE do schema.prisma
})
